# EasyAdmin Configuration
easy_admin:
    site_name: '<img src="/reserva/web/logo.jpg" />'
    design:
        brand_color: rgb(36, 56, 113)
    formats:
        number: '%d'
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
    entities:
        Usuario:
            class: AppBundle\Entity\Usuario
            list:
                actions:
                    - { name: 'reset', type: 'route', label: 'Cambiar Clave', icon: 'key' }
                fields:
                    - { property: usuario}
                    - { property: noSolapin }
                    - { property: nombre }
                    - { property: apellido }
                    - { property: segundoApellido }
                    - { property: roles, label: 'Roles', type: array }
            show:
                fields:
                    - { property: usuario, label: label.username }
            edit:
                fields:
                    usuario:
                        property: usuario
                    noSolapin:
                        property: noSolapin
                        label: Solapin
                    nombre:
                        property: nombre
                    apellido:
                        property: apellido
                    seg:
                        property: segundoApellido
                    roles:
                        property: roles
                        label: 'Roles'
                        type: entity
                        type_options:
                            class: AppBundle\Entity\Rol
                            multiple: true
            new:
                fields:
                      noSolapin:
                          property: noSolapin
                          label: Solapin
                          css_class: 'col-sm-4'
                      nombre:
                          property: nombre
                          css_class: 'col-sm-4'
                      apellido:
                          property: apellido
                          css_class: 'col-sm-4'
                      seg:
                          property: segundoApellido
                          css_class: 'col-sm-4'
                      usuario:
                          property: usuario
                          css_class: 'col-sm-4'
                      roles:
                          property: roles
                          label: 'Roles'
                          css_class: 'col-sm-4'
                          type: entity
                          type_options:
                              class: AppBundle\Entity\Rol
                              multiple: true
                      clave:
                          property: clave
                          type: repeated
                          css_class: 'col-sm-4'
                          type_options:
                              type: password
                              first_options:
                                  label: 'Clave'
                              second_options:
                                  label: 'Repetir Clave'
        Rol:
            class: AppBundle\Entity\Rol
        UnidadMedida:
            class: AppBundle\Entity\UnidadMedida
        Producto:
            class: AppBundle\Entity\Producto
        Plato:
            class: AppBundle\Entity\Plato
            list:
                fields:
                    - { property: codigo}
                    - { property: nombre}
                    - { property: descripcion}
                    - { property: categoria}
                    - { property: precio}
        TipoMenu:
            class: AppBundle\Entity\TipoMenu
        Menu:
            class: AppBundle\Entity\Menu
        EstadoReservacion:
            class: AppBundle\Entity\EstadoReservacion