# EasyAdmin Configuration
easy_admin:
    site_name: '<img src="/projects/reserva/web/logo.jpg" />'
    design:
        brand_color: rgb(36, 56, 113)
        form_theme: 'form/bootstrap_3_layout.html.twig'
    formats:
        number: '%.2f'
    list:
        max_results: 10
        actions:
            #- { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
    entities:
        Usuario:
            class: AppBundle\Entity\Usuario
            list:
                title: 'Buscar usuario'
                actions:
                    - { name: 'cambiar_clave', type: 'route', label: 'Cambiar clave', icon: 'key' }
                fields:
                    - { property: noSolapin, format: '%d', label: 'No. Solapín', sortable: false }
                    - { property: nombre, sortable: false }
                    - { property: apellido, label: 'Primer Apellido', sortable: false }
                    - { property: segundoApellido, sortable: false }
                    - { property: usuario, sortable: false}
                    - { property: rol, sortable: false }
        Rol:
            class: AppBundle\Entity\Rol
            list:
                title: 'Buscar rol'
                fields:
                    - { property: rol, sortable: false }
                    - { property: nombre, sortable: false }
            edit:
                title: 'Modificar rol'
            new:
                title: 'Nuevo rol'
            form:
                fields:
                    rol:
                        property: rol
                        css_class: 'col-sm-4'
                    nombre:
                        property: nombre
                        css_class: 'col-sm-4'
        UnidadMedida:
            class: AppBundle\Entity\UnidadMedida
            list:
                title: 'Buscar unidad de medida'
                fields:
                    - { property: nombre, sortable: false }
                    - { property: abreviatura, sortable: false }
            new:
                title: 'Nueva unidad de medida'
            edit:
                title: 'Modificar unidad de medida'
            form:
                fields:
                    codigo:
                        property: nombre
                        css_class: 'col-sm-4'
                    descripcion:
                        property: abreviatura
                        css_class: 'col-sm-2'
        Producto:
            class: AppBundle\Entity\Producto
            list:
                title: 'Buscar producto'
                fields:
                    - { property: codigo, label: 'Código', sortable: false }
                    - { property: descripcion, label: 'Descripción',sortable: false }
            new:
                title: 'Nuevo producto'
            edit:
                title: 'Modificar producto'
            form:
                fields:
                      codigo:
                          property: codigo
                          css_class: 'col-sm-3'
                          label: 'Código'
                      descripcion:
                          property: descripcion
                          label: 'Descripción'
                          css_class: 'col-sm-5'
                      unidad:
                          property: unidadMedida
                          label: 'Unidad de medida'
                          css_class: 'col-sm-2'
                          type_options: { required: true }
        Plato:
            class: AppBundle\Entity\Plato
            list:
                title: 'Buscar plato'
                actions:
                    - { name: 'carta_tecnica', type: 'route', label: 'Carta Técnica', icon: 'folder' }
                fields:
                    - { property: codigo, format: '%d', label: 'Código', sortable: false }
                    - { property: nombre, sortable: false }
                    - { property: categoria, label: 'Categoría' ,sortable: false }
                    - { property: precio, sortable: false, label: 'Precio($)' }
            edit:
                title: 'Modificar Plato'
        TipoMenu:
            class: AppBundle\Entity\TipoMenu
        Menu:
            class: AppBundle\Entity\Menu
            list:
                fields:
                    - { property: fecha, sortable: false}
                    - { property: aprobado, type: boolean, sortable: false}
                    - { property: observaciones, sortable: false}
                    - { property: tipoMenu, label: 'Tipo de Menu', sortable: false}
            edit:
                title: 'Modificar Menu'
        EstadoReservacion:
            class: AppBundle\Entity\EstadoReservacion
        Categoria:
            class: AppBundle\Entity\Categoria
            list:
                title: 'Buscar categoría del plato'
                fields:
                    - { property: nombre, sortable: false }
            new:
                title: 'Nueva categoría del plato'
            edit:
                title: 'Modificar categoría del plato'
            form:
                fields:
                    codigo:
                        property: nombre
                        css_class: 'col-sm-3'
        Conversion:
            class: AppBundle\Entity\Conversion