# EasyAdmin Configuration
easy_admin:
    site_name: '<img src="/projects/reserva/web/logo.jpg" />'
    design:
        brand_color: rgb(36, 56, 113)
        form_theme: 'form/bootstrap_3_layout.html.twig'
    formats:
        number: '%.2f'
    list:
        max_results: 10
        actions:
            #- { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
    entities:
        Usuario:
            class: AppBundle\Entity\Usuario
            list:
                actions:
                    - { name: 'cambiar_clave', type: 'route', label: 'Cambiar Clave', icon: 'key' }
                fields:
                    - { property: noSolapin, sortable: false }
                    - { property: nombre, sortable: false }
                    - { property: apellido, label: 'Primer Apellido', sortable: false }
                    - { property: segundoApellido, sortable: false }
                    - { property: usuario, sortable: false}
                    - { property: rol, sortable: false }
        Rol:
            class: AppBundle\Entity\Rol
        UnidadMedida:
            class: AppBundle\Entity\UnidadMedida
            list:
                title: 'Unidad de Medida'
                fields:
                    - { property: nombre}
                    - { property: abreviatura }
            edit:
                title: 'Modificar Unidad de Medida'
            form:
                fields:
                    codigo:
                        property: nombre
                        css_class: 'col-sm-6'
                    descripcion:
                        property: abreviatura
                        css_class: 'col-sm-6'
        Producto:
            class: AppBundle\Entity\Producto
            list:
                fields:
                    - { property: codigo}
                    - { property: descripcion }
            new:
                fields:
                      codigo:
                          property: codigo
                          css_class: 'col-sm-3'
                      descripcion:
                          property: descripcion
                          css_class: 'col-sm-5'
                      unidad:
                          property: unidadMedida
                          css_class: 'col-sm-4'
            edit:
                title: 'Modificar Producto'
                fields:
                    codigo:
                        property: codigo
                        css_class: 'col-sm-3'
                    descripcion:
                        property: descripcion
                        css_class: 'col-sm-5'
                    unidad:
                        property: unidadMedida
                        css_class: 'col-sm-4'
        Plato:
            class: AppBundle\Entity\Plato
            list:
                actions:
                    - { name: 'carta_tecnica', type: 'route', label: 'Carta Técnica', icon: 'folder' }
                fields:
                    - { property: codigo, label: 'Código', sortable: false }
                    - { property: nombre, sortable: false }
                    - { property: categoria, label: 'Categoría' ,sortable: false }
                    - { property: precio, sortable: false }
            edit:
                title: 'Modificar Plato'
        TipoMenu:
            class: AppBundle\Entity\TipoMenu
        Menu:
            class: AppBundle\Entity\Menu
            list:
                fields:
                    - { property: fecha, sortable: false}
                    - { property: aprobado, type: boolean, sortable: false}
                    - { property: observaciones, sortable: false}
                    - { property: tipoMenu, label: 'Tipo de Menu', sortable: false}
            edit:
                title: 'Modificar Menu'
        EstadoReservacion:
            class: AppBundle\Entity\EstadoReservacion
        Categoria:
            class: AppBundle\Entity\Categoria
            list:
                fields:
                    - { property: nombre}
            edit:
                title: 'Modificar Categoria'
            form:
                fields:
                    codigo:
                        property: nombre
                        css_class: 'col-sm-6'
                    descripcion:
                        property: platos
                        css_class: 'col-sm-6'
        Conversion:
            class: AppBundle\Entity\Conversion