# EasyAdmin Configuration
easy_admin:
    site_name: '<img src="/projects/reserva/web/logo.jpg" />'
    design:
        brand_color: rgb(36, 56, 113)
        form_theme: 'form/bootstrap_3_layout.html.twig'
    formats:
        number: '%d'
    list:
        max_results: 10
        actions:
            #- { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
    entities:
        Usuario:
            class: AppBundle\Entity\Usuario
            list:
                actions:
                    - { name: 'cambiar_clave', type: 'route', label: 'Cambiar Clave', icon: 'key' }
                fields:
                    - { property: noSolapin }
                    - { property: usuario}
                    - { property: nombre }
                    - { property: apellido, label: 'Primer Apellido' }
                    - { property: segundoApellido }
                    - { property: roles, label: 'Roles', type: array }
        Rol:
            class: AppBundle\Entity\Rol
        UnidadMedida:
            class: AppBundle\Entity\UnidadMedida
            list:
                fields:
                    - { property: nombre}
                    - { property: abreviatura }
            edit:
                title: 'Modificar Unidad de Medida'
            form:
                fields:
                    codigo:
                        property: nombre
                        css_class: 'col-sm-6'
                    descripcion:
                        property: abreviatura
                        css_class: 'col-sm-6'
        #Este es una entrada para una entidad que sera manejada por EasyAdminBundle
        Producto:
            class: AppBundle\Entity\Producto
            #Esta es la pagina para listar (tabla)
            list:
                fields:
                    - { property: codigo}
                    - { property: descripcion }
            #Esta es la seccion para la pagina de crear (formulario)
            new:
                fields:
                      #Se organizan los campos por linea (la suma de las columnas debe ser 12)
                      codigo:
                          property: codigo
                          css_class: 'col-sm-3'
                      descripcion:
                          property: descripcion
                          css_class: 'col-sm-5'
                      unidad:
                          property: unidadMedida
                          css_class: 'col-sm-4'
            edit:
                title: 'Modificar Producto'
                fields:
                    codigo:
                        property: codigo
                        css_class: 'col-sm-3'
                    descripcion:
                        property: descripcion
                        css_class: 'col-sm-5'
                    unidad:
                        property: unidadMedida
                        css_class: 'col-sm-4'
        Plato:
            class: AppBundle\Entity\Plato
            list:
                fields:
                    - { property: codigo}
                    - { property: nombre}
                    - { property: norma}
                    - { property: categoria}
                    - { property: precio}
            edit:
                title: 'Modificar Plato'
#            form:
#                fields:
#                    nombre:
#                        property: nombre
#                        css_class: 'col-sm-3'
#                    norma:
#                        property: norma
#                        label: 'Norma a servir(g)'
#                        css_class: 'col-sm-3'
#                    precio:
#                        property: precio
#                        css_class: 'col-sm-3'
        TipoMenu:
            class: AppBundle\Entity\TipoMenu
        Menu:
            class: AppBundle\Entity\Menu
            list:
                fields:
                    - { property: aprobado}
                    - { property: fecha}
                    - { property: tipoMenu, label: 'Tipo de Menu'}
            edit:
                title: 'Modificar Menu'
        EstadoReservacion:
            class: AppBundle\Entity\EstadoReservacion
        Categoria:
            class: AppBundle\Entity\Categoria
            list:
                fields:
                    - { property: nombre}
            edit:
                title: 'Modificar Categoria'
            form:
                fields:
                    codigo:
                        property: nombre
                        css_class: 'col-sm-6'
                    descripcion:
                        property: platos
                        css_class: 'col-sm-6'
        Conversion:
            class: AppBundle\Entity\Conversion