security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
    providers:
        db_provider:
            entity: { class: AppBundle:Usuario, property: usuario }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_JEFE: ROLE_USER
        ROLE_JEFE_SERVICIO: ROLE_USER
        ROLE_ECONOMICO: ROLE_USER
        ROLE_ALMACENERO: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            #http_basic: ~
            form_login:
                check_path: security_login_check
                login_path: security_login_form
                csrf_provider: security.csrf.token_manager
            logout:
                path: security_logout
                #target: homepage
            provider: db_provider
            switch_user: { role: ROLE_ADMIN }

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }