<?php

namespace AppBundle\Entity;

/**
 * RecepcionProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepcionProductoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPorRangoDeFecha($rango)
    {
        $query = $this->createQueryBuilder('rp')
           ->select('rp');

        if (!is_null($rango)) {
            $query->join('rp.recepcion', 'r')
                ->andWhere('r.fecha >= :inicio')
                ->andWhere('r.fecha <= :fin')
                ->setParameter(':inicio', $rango['inicio'])
                ->setParameter(':fin', $rango['fin']);
        }

        return $query->getQuery()->getResult();
    }
}
